keyboard:
  features:
    double_south: true
  layers:
  - index: 0
    name: Layer 0
    id: null
    variant: null
  - index: 1
    name: Layer 1
    id: null
    variant: null
  - index: 2
    name: Layer 2
    id: null
    variant: null
  - index: 3
    name: Layer 3
    id: null
    variant: null
  - index: 15
    name: Layer 15
    id: null
    variant: null
keycodes:
  pre_process: []
  overrides: []
output:
  layout:
    width: 1600.0
    spacing:
      margin: 0.0
      inset: 20.0
  style:
    use_layer_colors_on_keys: true
    hold_symbol_position: outward
    border:
      width: 2.0
      radius: 10.0
    palette:
      overrides: {}
      neutral_color: '#6F768B'
      text_color: black
      key_label_color: white
      background_color: white
      border_color: black
      layers:
      - base_color: '#772828'
        color_index: 2
        gradient: null
      - base_color: '#774528'
        color_index: 2
        gradient: null
      - base_color: '#776328'
        color_index: 2
        gradient: null
      - base_color: '#6C7728'
        color_index: 2
        gradient: null
      - base_color: '#772843'
        color_index: 2
        gradient: null
    use_system_fonts: false
    show_layer_indicators: true
    show_layer_connectors: true
  keymap_title: null
  copyright: null
