keyboard:
  features:
    double_south: true
  layers:
  - id: _BASE
    index: 0
    label: BASE
    name: Letters
    variant: COLEMAK
  - id: _GAME
    index: 1
    label: GAME
    name: Gaming
    variant: null
  - id: _NAV
    index: 2
    label: NAV
    name: Navigation
    variant: null
  - id: _NUM
    index: 3
    label: NUM
    name: Numbers
    variant: null
  - id: _SYM
    index: 4
    label: SYM
    name: Symbols
    variant: null
  - id: _FUN
    index: 5
    label: FN
    name: Function Keys
    variant: null
  - id: _MED
    index: 6
    label: MED
    name: Multimedia
    variant: null
  - id: _SYS
    index: 7
    label: SYS
    name: System
    variant: null
  - id: _MBO
    index: 15
    label: MBO
    name: Mouse
    variant: null
keycodes:
  pre_process:
  - keycode: LSFT(KC_TAB)
    target: MKC_BKTAB
  - keycode: CKC_BSPC
    target: LT(_NAV, KC_BACKSPACE)
  - keycode: USER20
    target: LT(_NAV, KC_BACKSPACE)
  - keycode: CKC_SPC
    target: LT(_NUM, KC_SPACE)
  - keycode: USER21
    target: LT(_NUM, KC_SPACE)
  - keycode: CKC_TAB
    target: LT(_SYM, KC_TAB)
  - keycode: USER22
    target: LT(_SYM, KC_TAB)
  - keycode: CKC_BKTAB
    target: LT(_FUN, MKC_BKTAB)
  - keycode: USER23
    target: LT(_FUN, MKC_BKTAB)
  - keycode: MB_ESC
    target: MT(MOD_LALT, KC_ESC)
  - keycode: USER29
    target: MT(MOD_LALT, KC_ESC)
  overrides:
  - keycode: MKC_BKTAB
    target: '%%nf-md-keyboard_tab_reverse;'
  - keycode: CKC_SMSFT
    target: '%%nf-md-brain; @@KC_LEFT_SHIFT;'
  - keycode: MKC_APPWIN
    target: '@@KC_LEFT_CTRL; @@KC_LEFT_GUI; @@KC_DOWN;'
  - keycode: MKC_DKTN
    target: '@@KC_LEFT_CTRL; @@KC_LEFT_GUI; @@KC_RIGHT;'
  - keycode: MKC_DKTP
    target: '@@KC_LEFT_CTRL; @@KC_LEFT_GUI; @@KC_LEFT;'
  - keycode: MKC_SHDKT
    target: '%%nf-md-monitor;'
  - keycode: MKC_SHNOT
    target: '%%nf-md-bell;'
  - keycode: MKC_SPFND
    target: '%%nf-md-magnify; %%nf-md-file_search;'
  - keycode: ML_ALT
    target: '@@KC_LEFT_ALT; OPT'
  - keycode: ML_CMD
    target: '@@KC_LEFT_GUI; CMD'
  - keycode: MB_SFT
    target: '@@KC_BTN1;'
  - keycode: MB_ALT
    target: '@@KC_BTN2;'
  - keycode: MB_GUI
    target: '@@KC_BTN3;'
  - keycode: MB_CTL
    target: '@@KC_BTN4;'
  - keycode: USER24
    target: '@@CKC_SMSFT;'
  - keycode: USER25
    target: '@@MB_SFT;'
  - keycode: USER26
    target: '@@MB_ALT;'
  - keycode: USER27
    target: '@@MB_GUI;'
  - keycode: USER28
    target: '@@MB_CTL;'
  - keycode: KC_ESC
    target: "\u238B\_ESC"
output:
  layout:
    width: 1600.0
    spacing:
      margin: 0.0
      inset: 20.0
  style:
    use_layer_colors_on_keys: false
    hold_symbol_position: outward
    border:
      width: 2.0
      radius: 10.0
    palette:
      overrides:
        azure: '#276e76'
        black: '#4f4f4f'
        blue: '#272776'
        chartreuse: '#4f7627'
        coral: '#763c27'
        cyan: '#277676'
        gold: '#766a27'
        goldenrod: '#766027'
        green: '#277627'
        magenta: '#762776'
        orange: '#764f27'
        pink: '#76274e'
        purple: '#4d2776'
        red: '#762727'
        springgreen: '#27764f'
        teal: '#277676'
        turquoise: '#3e605c'
        white: '#4f4f4f'
        yellow: '#767627'
      neutral_color: '#70768B'
      text_color: '#1b1b1b'
      key_label_color: '#FFF'
      background_color: '#FFF'
      border_color: '#1b1b1b'
      layers:
      - base_color: '#347156'
        color_index: 2
        gradient: null
      - base_color: '#3E605C'
        color_index: 2
        gradient: null
      - base_color: '#89511C'
        color_index: 2
        gradient: null
      - base_color: '#41687E'
        color_index: 2
        gradient: null
      - base_color: '#8C3B2C'
        color_index: 2
        gradient: null
      - base_color: '#5F4B7E'
        color_index: 2
        gradient: null
      - base_color: '#7E6E1E'
        color_index: 2
        gradient: null
      - base_color: '#9C2927'
        color_index: 2
        gradient: null
      - base_color: '#8C3396'
        color_index: 2
        gradient: null
    use_system_fonts: false
    show_layer_indicators: true
  keymap_title: null
  copyright: (c) Thiago Alves
