keyboard:
  features:
    double_south: true
  layers:
  - index: 0
    id: _BASE
    name: Letters
    variant: COLEMAK
  - index: 1
    id: _QWT
    name: Letters
    variant: QWERTY
  - index: 2
    id: _GAM1
    name: Gaming
    variant: WASD
  - index: 3
    id: _GAM2
    name: Gaming
    variant: NUMBERS
  - index: 4
    id: _NAV
    name: Navigation
    variant: null
  - index: 5
    id: _NUM
    name: Numbers
    variant: null
  - index: 6
    id: _SYM
    name: Symbols
    variant: null
  - index: 7
    id: _FUN
    name: Function Keys
    variant: null
  - index: 8
    id: _MED
    name: Multimedia
    variant: null
  - index: 14
    id: _SYS
    name: System
    variant: null
  - index: 15
    id: _MBO
    name: Mouse
    variant: null
keycodes:
  pre_process:
  - keycode: LSFT(KC_TAB)
    target: MKC_BKTAB
  - keycode: CKC_BSPC
    target: LT(_NAV, KC_BACKSPACE)
  - keycode: USER20
    target: LT(_NAV, KC_BACKSPACE)
  - keycode: CKC_SPC
    target: LT(_NUM, KC_SPACE)
  - keycode: USER21
    target: LT(_NUM, KC_SPACE)
  - keycode: CKC_TAB
    target: LT(_SYM, KC_TAB)
  - keycode: USER22
    target: LT(_SYM, KC_TAB)
  - keycode: CKC_BKTAB
    target: LT(_FUN, MKC_BKTAB)
  - keycode: USER23
    target: LT(_FUN, MKC_BKTAB)
  - keycode: MB_ESC
    target: MT(MOD_LOPT, KC_ESC)
  - keycode: USER29
    target: MT(MOD_LOPT, KC_ESC)
  overrides:
  - keycode: MKC_BKTAB
    target: '%%nf-md-keyboard_tab_reverse;'
  - keycode: CKC_SMSFT
    target: '%%nf-md-brain; @@KC_LEFT_SHIFT;'
  - keycode: MKC_APPWIN
    target: '%%nf-md-view_dashboard_outline;'
  - keycode: MKC_DKTN
    target: '%%nf-md-monitor;%%nf-cod-triangle_right;'
  - keycode: MKC_DKTP
    target: '%%nf-cod-triangle_left;%%nf-md-monitor;'
  - keycode: MKC_SHDKT
    target: '%%nf-md-monitor;'
  - keycode: MKC_SHNOT
    target: '%%nf-md-bell;'
  - keycode: MKC_SPFND
    target: '%%nf-md-magnify; %%nf-md-file_search;'
  - keycode: ML_ALT
    target: '@@KC_LEFT_ALT; OPT'
  - keycode: ML_CMD
    target: '@@KC_LEFT_GUI; CMD'
  - keycode: MB_SFT
    target: '@@KC_BTN1;'
  - keycode: MB_ALT
    target: '@@KC_BTN2;'
  - keycode: MB_GUI
    target: '@@KC_BTN3;'
  - keycode: MB_CTL
    target: '@@KC_BTN4;'
  - keycode: USER24
    target: '@@CKC_SMSFT;'
  - keycode: USER25
    target: '@@MB_SFT;'
  - keycode: USER26
    target: '@@MB_ALT;'
  - keycode: USER27
    target: '@@MB_GUI;'
  - keycode: USER28
    target: '@@MB_CTL;'
  - keycode: KC_ESC
    target: "\u238B\_ESC"
  symbol_legend_aliases:
    CKC_BSPC: KC_BSPC
    CKC_TAB: KC_TAB
    MB_SFT: KC_BTN1
    MB_ALT: KC_BTN2
    MB_GUI: KC_BTN3
    MB_CTL: KC_BTN4
    MB_ESC: KC_ESC
  symbol_descriptions:
    Modifiers:
      CKC_SMSFT: Smart shift
    Navigation:
      MKC_BKTAB: Shift tab
    Desktop:
      MKC_APPWIN: Show app windows
      MKC_DKTN: Next space
      MKC_DKTP: Previous space
      MKC_SHDKT: Show desktop
      MKC_SHNOT: Show notifications
      MKC_SPFND: Spotlight search

output:
  style:
    use_layer_colors_on_keys: false
    hold_symbol_position: outward
    border:
      width: 2.0
      radius: 10.0
    palette:
      overrides:
        azure: '#276e76'
        black: '#4f4f4f'
        blue: '#272776'
        chartreuse: '#4f7627'
        coral: '#763c27'
        cyan: '#277676'
        gold: '#766a27'
        goldenrod: '#766027'
        green: '#277627'
        magenta: '#762776'
        orange: '#764f27'
        pink: '#76274e'
        purple: '#4d2776'
        red: '#762727'
        springgreen: '#27764f'
        teal: '#277676'
        turquoise: '#3e605c'
        white: '#4f4f4f'
        yellow: '#767627'
      neutral_color: '#70768B'
      text_color: '#1b1b1b'
      key_label_color: '#FFF'
      background_color: '#FFF'
      border_color: '#1b1b1b'
      layers:
      - base_color: '#347156'
        color_index: 2
        gradient: null
      - base_color: '#2F898B'
        color_index: 2
        gradient: null
      - base_color: '#355A93'
        color_index: 2
        gradient: null
      - base_color: '#0C7595'
        color_index: 2
        gradient: null
      - base_color: '#89511C'
        color_index: 2
        gradient: null
      - base_color: '#41687E'
        color_index: 2
        gradient: null
      - base_color: '#8C3B2C'
        color_index: 2
        gradient: null
      - base_color: '#5F4B7E'
        color_index: 2
        gradient: null
      - base_color: '#7E6E1E'
        color_index: 2
        gradient: null
      - base_color: '#9C2927'
        color_index: 2
        gradient: null
      - base_color: '#8C3396'
        color_index: 2
        gradient: null
    use_system_fonts: false
    show_layer_indicators: true
    show_layer_connectors: true
    show_transparent_fallthrough: true
  keymap_title: Miryoku-inspired Layout
  copyright: "\xA9 2025, Thiago Alves"
